### ISSUE TITLE
Additional Config Options for VLAN.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#104]
### Updates ->

- VLAN Member Mode update, change following ->
      - tagged -> TRUNK 
      - untagged -> ACCESS

- admin_sts -> enabled

### Additional Editable Config Options ->

- Description -> json key name “description”
- Autostate -> json key name “autostate”
- Anycast Address -> json key name “sag_ip_address”, Format should be checked and be like- 10.10.10.10/24, There should be a delete option for this. An empty value can be considered to be a delete operation.
- IP Address -> json key name “ip_address”, Format should be checked and be like- 10.10.10.10/24, There should be a delete option for this. An empty value can be considered to be a delete operation.
>**_Note_** -> IP Address and Anycast Address can not be assigned together, either one of them can be assigned at once. A check should be implemented.

All editable params should be available in add VLAN pop-up.
Test cases in test_vlan.py in orca_backend can be used as a reference.
Remaining params (not mentioned above) editable or non-editable, should remains as it is. 

Pull orca_backend and updated dependencies, orca_nw_lib should be at version 1.3.8

**Comment by kamalkrbh** [comment]
I dont see changes done in this PR in the main branch.

**Comment by vivek-metricdust** [comment]
- [ ] In vlan member selection by default the selected item must be empty.
- [ ] Autostate of vlan must be a dropdown with "enable" and "disable" options.
- [ ] In vlan id Ip is selected autostate must be disabled and vice versa.
- [ ] in vlan status must be renamed to admin status.
