### ISSUE TITLE
Connection to server lost.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#145]
UI remains silient if the server is closed, user might keep on doing operations without any response for the requests.
Another use case is - if db is deleted and recreated and server is restarted and ui is still running, UI operations will fail without any specific error but actually it is getting failed due to login user has been deleted which was in the sqllite database.

**Comment by vivek-metricdust** [comment]
PR consist of new package so

- need to delete node modules folder
- need to delete package-lock.json file
- and perform npm i to install the packages

**Comment by kamalkrbh** [comment]
@vivek-metricdust , Alert should come only once per request , after all timeouts have happened. Currently the alert keeps poping up again and again for single request.

**Comment by vivek-metricdust** [comment]
> [@vivek-metricdust](https://github.com/vivek-metricdust) , Alert should come only once per request , after all timeouts have happened. Currently the alert keeps poping up again and again for single request.

fixes in [5a19493](https://github.com/STORDIS/orca_ui/pull/150/commits/5a19493407307dcd30c9e7b662026878d0e071d5)

**Comment by kamalkrbh** [comment]
@vivek-metricdust , It looks it is still not fixed, tried several times but similar behaviour. Alert show up for every retry.
Moving to changes requested again.

**Comment by kamalkrbh** [comment]
@vivek-metricdust , I still see the issues when backend is not running and trying to login says "invalid credetials" which is in correct. Also clear log panel says nothing when backend is not running.
