### ISSUE TITLE
Separate columns for trunk and access vlans in Portchannel

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_ui#151]
UI Need to adapt changes from [#48](https://github.com/STORDIS/orca_nw_lib/issues/48) 
i.e. No separate column for trunk and access vlans instead one column named "interface mode" another "vlan"

**Comment by kamalkrbh** [comment]
@vivek-metricdust , When choosing vlan in trunk mode, as soon as user select a vlan it should not appear again in drop down. and as soon as user removes them from drop down they can reappear in dropdown for selection.

As soon as user changes the mode from Trunk to Access , already configured list of vlans for trunk mode should be cleared (only on UI) and should be available in dropdown for user to configure the access mode, also should be checked that in access mode no more than one vlan can be selected.
Similarly when user switches from Access mode to Trunk list of already selected Vlans should be cleared (only on UI) and should be again available in drop down for selection for Trunk configuration.

**Comment by vivek-metricdust** [comment]
> [@vivek-metricdust](https://github.com/vivek-metricdust) , When choosing vlan in trunk mode, as soon as user select a vlan it should not appear again in drop down. and as soon as user removes them from drop down they can reappear in dropdown for selection.
> 
> As soon as user changes the mode from Trunk to Access , already configured list of vlans for trunk mode should be cleared (only on UI) and should be available in dropdown for user to configure the access mode, also should be checked that in access mode no more than one vlan can be selected. Similarly when user switches from Access mode to Trunk list of already selected Vlans should be cleared (only on UI) and should be again available in drop down for selection for Trunk configuration.
> 
> Also, Instead of just showing the json it would be better to show in more user friendly text like - Trunk-Vlan1, Vlan2 or Access - Vlan1

all the changes mentioned bellow are fixed in and PR is updated 

- in table for column access vlan the display is like TRUNK - vlan1, vlan2 respectively
- check for access vlan added there can only be one access vlan
- when the vlan or ethernet is selected that will be removed from the dropdown list and when it is removed from the selection it will be added back to dropdown. NOTE: the addition will be at last the recently removed (from selection) will be last option in dropdown
- when we switch from access vlan or from trunk vlan the selected vlan will be cleared and list in dropdown will have  all the vlans and ethernets respectively
- when we select the interface mood as access then only one vlan can be selected and if we selected the another vlan it will replace the current selected vlan
