### ISSUE TITLE
Interface Breakout support in UI

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_ui#158]
- [x]  Interface tab must have a new column as - breakout 
the values will be a Boolean (Yes / No)
if no show "No" in the cell
if yes show the list 
- [x] break_out status - current status of breakout
- [x] Deletion of the breakout - show none in the list which will delete the breakout

![Image](https://github.com/user-attachments/assets/1ff56f71-87c4-44fe-a9ac-952d638b9ca3)

**Comment by vivek-metricdust** [comment]
PR is created but

- UI changes is dependent on backend changes [#72](https://github.com/STORDIS/orca_nw_lib/issues/72)
- These is a known bug that when broken port are changed to None ( 1.e, delete api is called for breakout) the newly created broken port will still be seen but status will be changed

**Comment by vivek-metricdust** [comment]
PR has been updated with the changes supporting the IP address for the interface.
All the CRUD operation for IP Address are added

**Comment by kamalkrbh** [comment]
![Image](https://github.com/user-attachments/assets/e9c4a84a-32cd-47ee-8af7-2fee4673fc98)

Not showwing "Not Supported" for other Ethernet. Also Drop down List contains "None, null".

**Comment by vivek-metricdust** [comment]
> ![Image](https://github.com/user-attachments/assets/e9c4a84a-32cd-47ee-8af7-2fee4673fc98)
> 
> Not showwing "Not Supported" for other Ethernet. Also Drop down List contains "None, null". As seen in the task not all the ckeckboxes are checked, was this actually ready for review ?

This can be issue due to corrupted DB
