### ISSUE TITLE
Interface Primary/Secondary IP configuration.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#165]
Related Backend Task :
Interface Primary/Secondary IP configuration.
[#74](https://github.com/STORDIS/orca_backend/issues/74)

UI Task.
IP of an interface should have additional attribute Type "Primary" or "secondary", configuration and display should adapt to the attribute.
For display it can be shown like 10.10.10.10/24 : Secondary , 12.12.12.12/30 : Primary. For the configuration of IP there can be a small form which takes IP and the type can be picked from a drop down consisting 2 elements "Promary, Secondary".
In the backend there will be only one boolean property "secondary" on the basis of its boolean value UI should determine the type of IP for display and vice-versa while configuring.

**Comment by vivek-metricdust** [comment]
found a feature that there can be multiple secondary ip address. Need to make changes accordingly to support it
