### ISSUE TITLE
Support for ZTP in ORCA - UI

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_ui#173]
# ZTP & DHCP Config

### orca_ui
In the SONiC setup window, UI should have a drop down containing all the releases available in the orca. User can either provide a url (as done currently) or can select one of the image file name from the drop down. backend will generate the http url for the image file selected from the drop down as those files are hosted in orca_backend.
 

### orca_ui
- A new section in left hand panel called - “ZTP & DHCP”. We need to create a json file editor here. which show the list of ztp files already created, should also allow editting of those files and save them usign backend APIs in orca_backend. 
- The panel looks like the code editors where on left side we have files list and on the right side an editor. Also there should be a warnig mechanism if user closes the window when there are unsaved changes in the editor.

### orca_ui
- Under the ZTP & DHCP section, on the top of editor panel there should be UI tools to save DHCP servers credentials (IP, User and Password) also list all the DHCP servers configured, in the editor list list dhcpd.conf and all backup files fro mall DHCP servers configures, as those files may have same name , to distinguish them server wise show the DHCP server IP in gray in from of those files.

### orca_ui
Under Device Info section , There should be one more table panel "Available SONiC Devices in Network", Those are the devices which are available but not yet discovered in ORCA, In the table contains IP and MAC of the device and a check box in the last column, the last column name is Select for discovery. And a Button can be placed at the Top of this table "Discover Selected". Clicking on this button orca just triggeres the discovery of selected devices from the avaialble device table. and removes them from avaialble device table as they will appear in the table above which display all devices already discovere in ORCA.

related backend - [orca_backend #70](https://github.com/STORDIS/orca_backend/issues/70)

**Comment by vivek-metricdust** [comment]
![Image](https://github.com/user-attachments/assets/f65301b4-01f1-4530-bb05-cf7d1bf099a9)

The ui look similar to the diagram

and the package used for the code editor is -  [monaco-react](https://github.com/suren-atoyan/monaco-react)

**Comment by kamalkrbh** [comment]
Following to be fixed after demo -

- [ ] Tool tip for unsaved dhcp files says "File Saved".
- [ ] Closing the tab with unsaved chages should discard the unsaved content, the Alert should say the respectively.
- [ ] Checksum should decide whether a file is updated or not, currently pressing save button multiple times creates the backup files with same content.
- [ ] uneditable template ZTP and dhcp files should be present in editor.
- [ ] Available device table , the available device list comes from backend after scanning dhcp lease file.
- [ ] ZTP file renaming facility.
- [ ] tool tip on ssh connection status.

**Comment by vivek-metricdust** [comment]
PR has been created [Ztp Feature #179](https://github.com/STORDIS/orca_ui/pull/179)
NOTE -  new package has been added - need to perform npm i for installation
