### ISSUE TITLE
Discovery Enhancements - Incase of subnet address provided -UI

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_ui#176]
In case when a user have provided a subnet address , Instead of right away triggering discovery, first the user should be provided with list of sonic devices with system info so that user can select one or more or all the devices from the list which can then be discovered.
Also lets fix the network bit to 22 as lesser bits will result into more IPs to scan for. So any network address which has mask bits less than 22 should be discarded.
Discover all should be enabled for sonic devices in the scan result table.

**Comment by kamalkrbh** [comment]
@rahul-1475 , There might be some refactoring in release API required to support this.
