### ISSUE TITLE
GUI Configuration for VLAN

### ISSUE THREAD

**Issue by BinishRawal** [STORDIS/orca_ui#49]
For Vlan

- [x] 1. Make member interface field editable and give checkbox for each memeber interface as tag or untag.
- [x] 2. Make MTU and Admin Status also editable.
- [x] 3. While Apply Config JSON body should have {mgt_ip, name, vlanid, <appending the editable fields>}.
- [x] 4. To add VLAN in modal form give all fields except operation status.
- [x] 5. For deleting use same method as we used for port channel.

**Comment by kamalkrbh** [comment]
Merged the pull request and logged the issues which are still there at #77 .
