### ISSUE TITLE
Datatable doesn't get updated in case of partial operation success.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#54]
When deleting all/multiple portchannels if one of them fails to delete, the table doesn’t remove any of them from data table.
It is also observed that data table isn't updated of multiple configurations are applied and there is partial success. For example in case of configuring interface select correct params for some and incorrect mtu for one of those datatable isn't updated after partially successfull operation.

**Comment by vivek-metricdust** [comment]
this issue will be fixed once the log panel backend is integrate. [#14](https://github.com/STORDIS/orca_backend/issues/14)

**Comment by vivek-metricdust** [comment]
`this issue is solved there logs are getting logged but due to single status code in response bot are logged as failed but the result is giving proper message.
sample responce: 
`{
    "result": [
        "PUT request failed : {'mgt_ip': '10.10.229.58', 'name': 'Ethernet76', 'enabled': True, 'mtu': 12} Reason: SET failed: Translib Redis Error: CVL Failure: 1,001: ErrCode[1001]: ErrDetails[Internal Unknown Error], Msg[Field \"mtu\" has invalid value], ConstraintErrMsg[Invalid MTU value], Table[PORT:[Ethernet76]], Field[mtu:]",
        "\n",
        "PUT request successful : {'mgt_ip': '10.10.229.58', 'name': 'Ethernet72', 'enabled': True}"
    ]
}`

**Comment by kamalkrbh** [comment]
OK, closing it then,
The status issue for combined request is to be fixed under orca_backend#22
