### ISSUE TITLE
Members are not visible in Juypter notebook but when we add members via Frontend or Postman(API) it give Success result.

### ISSUE THREAD

**Issue by BinishRawal** [STORDIS/orca_ui#57]

**Comment by BinishRawal** [comment]
When we run this command "url=f"https://{device_ip_list[0]}/restconf/data/sonic-vlan:sonic-vlan/VLAN/VLAN_LIST"
send_req(HttpRequest.GET,url)" in Juypter Notebook the VLAN_LIST doesn't show  Member Interface which are assigend to desired VLAN.  Member Interface are visible in "VLAN_MEMBER_TABLE_LIST".

VLAN_MEMBER_TABLE_LIST:-


![Image](https://github.com/STORDIS/orca_ui/assets/97798156/1d8da7b4-d7c2-4956-9010-4102fa590624)



VLAN_LIST:-


![Image](https://github.com/STORDIS/orca_ui/assets/97798156/a18f57fb-f165-40d3-898b-068a31a7898c)

**Comment by vivek-metricdust** [comment]
this issue is no more existing as the output consist of vlan list and vlan member


![Image](https://github.com/STORDIS/orca_ui/assets/157693017/37eb0d20-f5ab-41d4-ae26-1e1d130b22be)
