### ISSUE TITLE
Configuration status isn't visible after switching tabs.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#67]
Once a configuration in any of the tab is applied using "Apply Config" button, It may show "In progress" , "Success" or "Failure".
If user switches the tab while the configuration is already in progress the staus isn't visible any more.
Best would be to submit the configs requests to a queue and display in log panel with an option to cancle any ongoing config. 
Th log panel then can hvae 4 columns 
- Timestamp
- The request Json (actual config task)
- Status (Success/Fail with reason)
- The processing time.

The limit has to be applied on unfinished tasks i.e. There can not in progress tasks more than a certain limit. Hence there are 2 limiting factors one for total number of rows in the panel (for logging panel) and can be decided by user on the other hand there should be additional limit on  "on-going " tasks that user can not configure but decided by backend.

**Comment by kamalkrbh** [comment]
Queuing mechanism should be implemented on backend, with a map of task to task_id. Also All the logs should be stored in Django database (SQL Lite).

**Comment by vivek-metricdust** [comment]
as log pannel is integrated this issue is solved except the Queuing mechanism.

**Comment by kamalkrbh** [comment]
This is partly diverging towards implemetation of queuing the tasks and partly fixed with the introduction of log panel, the real time request status is always visible in Log panel.
