### ISSUE TITLE
Login and user authentication for UI

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_ui#70]

**Comment by vivek-metricdust** [comment]
Completed the Ui and functionality of login and logout with hardcoded values. Waiting for the Apis to get merged. Secure ORCA backend.
[#3](https://github.com/STORDIS/orca_backend/issues/3)

**Comment by kamalkrbh** [comment]
@vivek-metricdust If all done with hardcoded values, create a pull request, you can update once the backend APIs are available.

**Comment by kamalkrbh** [comment]
dependent upon - [#3](https://github.com/STORDIS/orca_backend/issues/3)

**Comment by vivek-metricdust** [comment]
tested with #3 and removed the hard coded authentication and also merged with the head of main branch.

**Comment by vivek-metricdust** [comment]
should integrate with backend
